sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    database: ${MYSQL_DATABASE:sky_take_out}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
  alioss:
    endpoint: ${ALI_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    access-key-id: ${ALI_OSS_KEY:}
    access-key-secret: ${ALI_OSS_SECRET:}
    bucket-name: ${ALI_OSS_BUCKET:}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    #redis默认创建的15个数据库DB0-15，每个数据库相互独立，在此可规定选择的数据库(默认是0)
    database: ${REDIS_DATABASE:1}
  wechat:
    appid: ${WECHAT_APP_ID:}
    secret: ${WECHAT_APP_SECRET:}
    mchid: ${WECHAT_MCH_ID:} #商户号
    mchSerialNo: ${WECHAT_SERIAL_NO:} #商户API证书的证书序列号
    privateKeyFilePath: ${WECHAT_PRIVATE_KEY_PATH:D:\apiclient_key.pem} #商户私钥文件
    apiV3Key: ${WECHAT_API_V3_KEY:} #证书解密的密钥
    weChatPayCertFilePath: ${WECHAT_PLATFORM_CERT:D:\wechatpay_cert.pem} #平台证书
    notifyUrl: ${WECHAT_NOTIFY_URL:https://localhost/notify/paySuccess} #支付成功的回调地址:微信后台来访问的地址，需要公网ip
    refundNotifyUrl: ${WECHAT_REFUND_NOTIFY_URL:https://localhost/notify/refundFail} #退款成功的回调地址:微信后台来访问的地址，需要公网ip，尚未开发
  shop:
    address: ${SHOP_ADDRESS:天津市南开区卫津路92号}
  baidu:
    ak: ${BAIDU_AK:}
